use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    generate_noun_phf(
        Path::new("data/noun_data.tsv"),
        &Path::new(&out_dir).join("noun_phf.rs"),
    );

    generate_verb_phf(
        Path::new("data/verb_data.tsv"),
        &Path::new(&out_dir).join("verb_phf.rs"),
    );

    generate_adj_phf(
        Path::new("data/adj_data.tsv"),
        &Path::new(&out_dir).join("adj_phf.rs"),
    );

    println!("cargo::rerun-if-changed=data/");
}

fn generate_noun_phf(input: &Path, output: &Path) {
    let data = fs::read_to_string(input)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", input.display(), e));

    let mut out = fs::File::create(output).unwrap();

    writeln!(out, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(
        out,
        "pub static PLURAL_MAP: phf::Map<&'static str, &'static str> = phf_map! {{"
    )
    .unwrap();

    for line in data.lines().skip(1) {
        let mut parts = line.split('\t');
        if let (Some(word), Some(plural)) = (parts.next(), parts.next()) {
            writeln!(out, "    \"{}\" => \"{}\",", word, plural).unwrap();
        }
    }

    writeln!(out, "}};\n").unwrap();
    writeln!(
        out,
        "pub fn get_plural(word: &str) -> Option<&'static str> {{ PLURAL_MAP.get(word).copied() }}"
    )
    .unwrap();
}

fn generate_verb_phf(input: &Path, output: &Path) {
    let data = fs::read_to_string(input)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", input.display(), e));

    let mut out = fs::File::create(output).unwrap();

    writeln!(out, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(
        out,
        "/// (3rd person singular, past, present participle, past participle)"
    )
    .unwrap();
    writeln!(
        out,
        "pub static VERB_MAP: phf::Map<&'static str, (&'static str, &'static str, &'static str, &'static str)> = phf_map! {{"
    )
    .unwrap();

    for line in data.lines().skip(1) {
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() == 5 {
            writeln!(
                out,
                "    \"{}\" => (\"{}\", \"{}\", \"{}\", \"{}\"),",
                parts[0], parts[1], parts[2], parts[3], parts[4]
            )
            .unwrap();
        }
    }

    writeln!(out, "}};\n").unwrap();
    writeln!(
        out,
        "pub fn get_verb_forms(infinitive: &str) -> Option<(&'static str, &'static str, &'static str, &'static str)> {{"
    )
    .unwrap();
    writeln!(out, "    VERB_MAP.get(infinitive).copied()").unwrap();
    writeln!(out, "}}").unwrap();
}

fn generate_adj_phf(input: &Path, output: &Path) {
    let data = fs::read_to_string(input)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", input.display(), e));

    let mut out = fs::File::create(output).unwrap();

    writeln!(out, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(out, "/// (comparative, superlative)").unwrap();
    writeln!(
        out,
        "pub static ADJECTIVE_MAP: phf::Map<&'static str, (&'static str, &'static str)> = phf_map! {{"
    )
    .unwrap();

    for line in data.lines().skip(1) {
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() == 3 {
            writeln!(
                out,
                "    \"{}\" => (\"{}\", \"{}\"),",
                parts[0], parts[1], parts[2]
            )
            .unwrap();
        }
    }

    writeln!(out, "}};\n").unwrap();
    writeln!(
        out,
        "pub fn get_adjective_forms(positive: &str) -> Option<(&'static str, &'static str)> {{"
    )
    .unwrap();
    writeln!(out, "    ADJECTIVE_MAP.get(positive).copied()").unwrap();
    writeln!(out, "}}").unwrap();
}
