[package]
name = "extractor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
csv.workspace = true
serde.workspace = true
serde_json.workspace = true
english-core.workspace = true
# english is only used for benchmarking
english.workspace = true
